name: Sample Workflow
on:
    push:
    workflow_dispatch:
    pull_request:
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Echo My name
              run: echo "Aastvik"
            - name: Echo Clg
              run: echo "DTU"
